In [1]:
# Loaded variable 'df' from URI: c:\Users\Pendu\Downloads\2024-05-24_14-24-39_ScalableCapital-Broker-Transactions.csv
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Pendu\Downloads\29may2024 - 29may2024.csv")

In [2]:
df.tail()

,date,time,status,reference,description,assetType,type,isin,shares,price,amount,fee,tax,currency
21,2024-05-29,15:44:19,Executed,SCALkQjizUrgGhj,NVIDIA,Security,Sell,US67066G1040,21,"1.025,60","21.537,60","0,00","0,00",EUR
22,2024-05-29,14:40:49,Executed,SCALEkHfeTAJSua,NVIDIA,Security,Buy,US67066G1040,6,"1.048,00","-6.288,00","0,00","0,00",EUR
23,2024-05-29,13:30:54,Executed,SCALkYUdZoTb1sd,NVIDIA,Security,Buy,US67066G1040,15,"1.055,00","-15.825,00","0,00","0,00",EUR
24,2024-05-29,13:23:19,Executed,SCAL3mvByQD77wP,NVIDIA,Security,Sell,US67066G1040,21,"1.054,20","22.138,20","0,00","0,00",EUR
25,2024-05-29,10:50:01,Executed,SCAL4APHJ4Er79Z,NVIDIA,Security,Buy,US67066G1040,8,"1.039,80","-8.318,40","0,00","0,00",EUR

In [3]:
np.sum(df['amount'])

'25.821,12-5.936,40-18.968,1025.569,60-802,90-6.406,80-19.216,8026.580,00-6.370,80-20.162,8021.148,00-21.036,0028.101,60-6.234,00-21.789,6027.950,40-6.218,40-21.760,2029.125,60-6.188,40-22.682,0021.537,60-6.288,00-15.825,0022.138,20-8.318,40'

In [4]:
# Selecting subset of df for the date '2024-05-23'
df_subset = df[df['date'] == '2024-05-29']
df_subset.head()

,date,time,status,reference,description,assetType,type,isin,shares,price,amount,fee,tax,currency
0,2024-05-29,21:58:43,Executed,SCALxVwXUvXS3ST,Dell Technologies C,Security,Sell,US24703L2025,156,"165,52","25.821,12","0,00","0,00",EUR
1,2024-05-29,21:55:07,Executed,SCALyPPQdnoEcUC,Dell Technologies C,Security,Buy,US24703L2025,36,"164,90","-5.936,40","0,00","0,00",EUR
2,2024-05-29,21:45:32,Executed,SCALWxgCTpJcg5s,Dell Technologies C,Security,Buy,US24703L2025,115,"164,94","-18.968,10","0,00","0,00",EUR
3,2024-05-29,21:44:00,Executed,SCALkMcrQcbQHDi,NVIDIA,Security,Sell,US67066G1040,24,"1.065,40","25.569,60","0,00","0,00",EUR
4,2024-05-29,21:03:31,Executed,SCALkkdPd6xFVwZ,Dell Technologies C,Security,Buy,US24703L2025,5,"160,58","-802,90","0,00","0,00",EUR

In [5]:
converted = df_subset['amount'].str.replace('.', '').str.replace(',', '.')

C:\Users\Pendu\AppData\Local\Temp\ipykernel_61420\3879139768.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  converted = df_subset['amount'].str.replace('.', '').str.replace(',', '.')

In [6]:
converted = converted.astype(float)

In [8]:
np.sum(converted[:])-5239-8376

152.5200000000059

In [99]:
df_subset_2 = df[df['date'] == '2024-05-24']
df_subset_2.tail()

,date,time,status,reference,description,assetType,type,isin,shares,price,amount,fee,tax,currency
63,2024-05-24,13:17:18,Executed,SCALVugCCJYCtZ2,NVIDIA,Security,Sell,US67066G1040,9,"969,80","8.728,20","0,00","0,00",EUR
64,2024-05-24,13:10:31,Executed,SCALGanS893a86s,NVIDIA,Security,Buy,US67066G1040,1,"970,50","-970,50","0,00","0,00",EUR
65,2024-05-24,13:06:41,Executed,SCAL9p8Xcffy4wD,NVIDIA,Security,Buy,US67066G1040,5,"968,20","-4.841,00","0,00","0,00",EUR
66,2024-05-24,13:03:54,Executed,SCALJcX4vJi2ZAc,NVIDIA,Security,Buy,US67066G1040,8,"967,40","-7.739,20","0,00","0,00",EUR
67,2024-05-24,13:02:26,Executed,SCAL44kudZBytJm,NVIDIA,Security,Sell,US67066G1040,11,"965,60","10.621,60","0,00","0,00",EUR

In [126]:
df_subset_2

,date,time,status,reference,description,assetType,type,isin,shares,price,amount,fee,tax,currency
0,2024-05-24,21:51:26,Executed,SCALd7sRgWAeUzk,NVIDIA,Security,Sell,US67066G1040,6,"976,10","5.856,60","0,00","0,00",EUR
1,2024-05-24,21:39:54,Executed,SCAL3nbbS2WHf8C,NVIDIA,Security,Buy,US67066G1040,2,"977,60","-1.955,20","0,00","0,00",EUR
2,2024-05-24,21:34:42,Executed,SCALeq5BZEELPgf,NVIDIA,Security,Buy,US67066G1040,4,"976,90","-3.907,60","0,00","0,00",EUR
3,2024-05-24,21:29:22,Executed,SCALZzTYdfiLiDK,NVIDIA,Security,Sell,US67066G1040,10,"977,00","9.770,00","0,00","0,00",EUR
4,2024-05-24,20:46:21,Executed,SCAL8MAUChkGsMv,NVIDIA,Security,Buy,US67066G1040,1,"972,40","-972,40","0,00","0,00",EUR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,2024-05-24,13:17:18,Executed,SCALVugCCJYCtZ2,NVIDIA,Security,Sell,US67066G1040,9,"969,80","8.728,20","0,00","0,00",EUR
64,2024-05-24,13:10:31,Executed,SCALGanS893a86s,NVIDIA,Security,Buy,US67066G1040,1,"970,50","-970,50","0,00","0,00",EUR
65,2024-05-24,13:06:41,Executed,SCAL9p8Xcffy4wD,NVIDIA,Security,Buy,US67066G1040,5,"968,20","-4.841,00","0,00","0,00",EUR
66,2024-05-24,13:03:54,Executed,SCALJcX4vJi2ZAc,NVIDIA,Security,Buy,US67066G1040,8,"967,40","-7.739,20","0,00","0,00",EUR
67,2024-05-24,13:02:26,Executed,SCAL44kudZBytJm,NVIDIA,Security,Sell,US67066G1040,11,"965,60","10.621,60","0,00","0,00",EUR

In [114]:
converted_2 = df_subset_2['amount'].str.replace('.', '').str.replace(',', '.')
converted_2 = converted_2.astype(float)

C:\Users\Pendu\AppData\Local\Temp\ipykernel_41708\2008155704.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  converted_2 = df_subset_2['amount'].str.replace('.', '').str.replace(',', '.')

0     5856.6
1    -1955.2
2    -3907.6
3     9770.0
4     -972.4
       ...
62    4854.0
63    8728.2
64    -970.5
65   -4841.0
66   -7739.2
Name: amount, Length: 67, dtype: float64

In [120]:
#May 23 profit
np.sum(converted[:])+converted_2.values[-1]

131.899999999996

In [123]:
#may 24 profit
np.sum(converted_2[:-1])

-76.800000000002

In [124]:
converted_2.values[:-1]

array([ 5856.6, -1955.2, -3907.6,  9770. ,  -972.4, -1944.6, -2913.6,
       -3886.8,  3878.4, -3883.6, 10666.7,  -966.7,  -966.5, -1935.6,
       -2902.2, -3867.2,   966.1,  -967.2, 10633.7, -1930.4, -2894.7,
       -3859.6, -1930.4, 10601.8,  -967.2, -1933.2, -2896.2, -4818.5,
        8650.8, -3842.8, -4802.5,  4781.5, -4788. ,  5722.8,  5775. ,
       -1929.2, -3853.6, -5771.4,  9586. , -3848. , -5765.4,  9597. ,
       -3860. , -5782.8,  5769.6, -5780.4, 12502.1, -1916.8, -3826. ,
       -6679.4,  6657.7, -6735.4,  6751.5,  4831.5, -4821. , -6746.6,
        6729.1, -6758.5, 13545. ,  -967.1, -4848.5, -7758.4,  4854. ,
        8728.2,  -970.5, -4841. , -7739.2])

In [130]:
# Calculate the sum of values in converted_2.values such that each value is the sum of a series of values starting with a positive value followed by subsequent negative values until the next positive value.
# Initialize variables to store the cumulative sum and the list of sums
cumulative_sum = 0
sums = []

# Iterate through the values in converted_2.values
for value in converted_2.values[:-1]:
    if value > 0:
        if cumulative_sum != 0:
            sums.append(cumulative_sum)
        cumulative_sum = value  # Start a new sum series with the current positive value
    else:
        cumulative_sum += value  # Add the negative value to the current sum series

# Append the last series sum if it ends with negatives
if cumulative_sum != 0:
    sums.append(cumulative_sum)

# Print the list of sums
print(sums)

[-6.199999999999363, 52.59999999999991, -5.199999999999818, 28.5, -1.1000000000000227, 18.600000000001273, -13.300000000001091, 5.4999999999990905, -6.5, 5722.8, -5779.199999999999, -27.399999999999636, -45.80000000000018, -10.799999999999272, 79.90000000000146, -77.69999999999982, 6751.5, -6736.1, -29.399999999999636, -29.0, 4854.0, -4822.499999999999]